apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: your-catalog-image:latest
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: catalog-db-secret
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: catalog-db-secret
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: catalog-db-secret
                  key: dbname
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: catalog-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-db-secret
                  key: password