apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: your-orders-image:latest
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: orders-db-secret
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: orders-db-secret
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: orders-db-secret
                  key: dbname
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orders-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-db-secret
                  key: password