name: Terraform CI/CD

on:
  push:
    branches:
      - main       # triggers apply
      - 'feature/*' # triggers plan
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      AWS_REGION: eu-west-1 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3 # note to self: check this later on

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=terraform/environments/dev init

      - name: Terraform Validate
        run: terraform -chdir=terraform/environments/dev validate

      - name: Terraform Plan
        run: terraform -chdir=terraform/environments/dev plan -out=tfplan \
          -var="orders_db_username=${{ secrets.ORDERS_DB_USERNAME }}" \
          -var="orders_db_password=${{ secrets.ORDERS_DB_PASSWORD }}" \
          -var="catalog_db_username=${{ secrets.CATALOG_DB_USERNAME }}" \
          -var="catalog_db_password=${{ secrets.CATALOG_DB_PASSWORD }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=terraform/environments/dev apply -auto-approve tfplan \
          -var="orders_db_username=${{ secrets.ORDERS_DB_USERNAME }}" \
          -var="orders_db_password=${{ secrets.ORDERS_DB_PASSWORD }}" \
          -var="catalog_db_username=${{ secrets.CATALOG_DB_USERNAME }}" \
          -var="catalog_db_password=${{ secrets.CATALOG_DB_PASSWORD }}" \
          -var="carts_table_name=${{ secrets.CARTS_TABLE_NAME }}"
